### ISSUE TITLE
test_v3_vs_oti_properties.py is failing

### ISSUE THREAD

**Issue by jar398** [OpenTreeOfLife/oti#60] opened 2016-10-09 03:02 UTC
```
Running tests in ../../germinator/ws-tests/../../oti/ws-tests
....Config file "/Users/jar/otrepo/oti/ws-tests/test.conf" does not contain option "otihost" in section "host"
Traceback (most recent call last):
  File "test_v3_vs_oti_properties.py", line 21, in <module>
    CONTROLLER = DOMAIN_OTI + '/v3/studies'
TypeError: unsupported operand type(s) for +: 'NoneType' and 'str'
F
Passed 4 out of 5 tests.
Failures:  test_v3_vs_oti_properties.py
```

**Comment by jar398** [comment] 2016-10-30 23:51
I keep running into this. @kcranston I think you added this test. Are you going to take care of it or would you like me to? (I think I would just disable it, since I don't know what it's trying to do.)

If it gets past the first error (e.g. by changing otihost to apihost), it hits a second one, that otindex_result is unbound.

**Comment by kcranston** [comment] 2016-10-31 02:34
Deleted the file. Duplicate of #59

**Closed as completed by kcranston** 2016-10-31 02:34 UTC
